# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Glenn Livens
title: Industrieel Ingenieur Elektromechanica
email: glennlivens@hotmail.com
address: Boechout, Antwerpen
birthday: 06/04/1993
phone: +32 (0)474/33.67.68
website: https://GL6013.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: glennlivens
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Over Mij
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Ik zou mezelf beschrijven als betrouwbaar, gemotiveerd en met een gezonde ambitie. Ik vind
  flexibele uren en weekendwerk niet erg als een gezonde work-life balans behouden blijft. Alsook is reizen voor korte periodes geen probleem.
  Mijn professionele interesses zijn: projecten rond automatisatie (PLC/HMI/SCADA, robotica, digitalisatie, ...), optimaliseren en analyseren van productieprocessen. 


content:
  - title: Werkervaring # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Continental Automotive Benelux BV
        link: https://www.continental.com/en?lang=be
        # link_text: continental.com
        sub_title: Specialist Industrial Engineering Conditioning Area & PLV assembly 
        caption: November 2016 - Nu
        quote: >
          The future in motion!
        description: | # this will include new lines to allow paragraphs
          "Als werkvoorbereider IE heb ik technical ownership over twee productiezones. Hierbij sta ik in voor de continuïteit van de afdeling waardoor volgende zaken tot mijn takenpakket behoren: 
          Projecten uitwerken van A tot Z, Optimalisatiestudies (takttijd verbeteringen), PLC aanpassingen, Ondersteuning voor zowel kwaliteit als productie, intern en extern onderhoud coördineren, digitaliseren en verder automatiseren."
      - layout: left
        title: Caradon Stelrad N.V.
        link: www.stelrad.eu
        # link_text: boringcompany.com
        sub_title: Masterthesis student
        caption: 2015 - 2016
        description: | # this will include new lines to allow paragraphs
            Ontwerp maken voor laskop beugellasmachine (sterkteberekeningen, EEM-analyse, technische tekeningen, kostenraming), ontwerp realiseren, ontwerp testen, resultatenverwerking.

- title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Automatisatie
        description: | # this will include new lines to allow paragraphs
          - "PLC: TwinCAT 2, TwinCAT 3, TIA Portal V13-V16 S7, STEP7 simatic manager"
            - test
          - "HMI: TwinCAT 3 Visualisation, WinCC Flex 2008, TIA Portal WinCC"
          - "voorbeeldprojecten: Omzetten tekst gebaseerde HMI siemens protool naar volledige procesvisualisatie in TIA Portal WinCC, Integreren SQL database voor het loggen van procesparameters in TwinCAT 3, PLC wijzigen door volledig nieuwe koelgaggregaten in te programmeren."
      - layout: left
        title: Digitalisatie
        description: | # this will include new lines to allow paragraphs
          - "Programmeren: Visual Studio 2013-2019, basisprogramma's in VB.NET, C# vb. 2 Keyence scanners triggeren om DMC's te lezen en info wegschrijven naar SQL DB."
      - layout: left
        title: Sint-Gabrielcollege
        caption: 2005 - 2011
        sub_title: ASO
        description: | # this will include new lines to allow paragraphs
          Wetenschappen Wiskunde 6u  
          op het Sint-Gabrielcollege te Boechout.
          
  - title: Opleidingen # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KU Leuven
        caption: 2014 - 2016
        sub_title: Master IIW
        description: | # this will include new lines to allow paragraphs
          Master Industriële Ingenieurswetenschappen Manufacturing Engineering
          bij Technologiecampus De Nayer in Sint-Katelijne-Waver.
      - layout: left
        title: KU Leuven
        caption: 2011 - 2015
        sub_title: Bachelor IIW
        description: | # this will include new lines to allow paragraphs
          Bachelor Industriële Ingenieurswetenschappen Elektromechanica 
          bij Technologiecampus De Nayer in Sint-Katelijne-Waver.
      - layout: left
        title: Sint-Gabrielcollege
        caption: 2005 - 2011
        sub_title: ASO
        description: | # this will include new lines to allow paragraphs
          Wetenschappen Wiskunde 6u  
          op het Sint-Gabrielcollege te Boechout.
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
