# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Glenn Livens
title: Industrieel Ingenieur Elektromechanica
email: glennlivens@hotmail.com
#address: Boechout, Antwerpen
birthday: 06/04/1993
phone: +32 (0)474/33.67.68
website: https://GL6013.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: glennlivens
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: CV
#   icon: images/favicon.ico
#   url: images/profile.jpg

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Over Mij
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Ik zou mezelf beschrijven als betrouwbaar, gemotiveerd en met een gezonde ambitie. Ik vind
  flexibele uren (af en toe shiften of weekend) en reizen voor korte periodes niet erg zolang een gezonde work-life balans behouden kan blijven.
  
  Mijn professionele interesses zijn: 
  - Projecten rond automatisatie (PLC/HMI/SCADA, robotica, digitalisatie, ...)
  - Optimaliseren en analyseren van productieprocessen.
  - Toepassen van en op de hoogte blijven over de nieuwste technologiën
  
  Mijn andere interesses zijn: Sporten (Fietsen, Fitness, Snowboarden, Hiken), Reizen, ...
content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Automatisatie
        description: | # this will include new lines to allow paragraphs
          - Beckhoff TwinCAT 2 / TwinCAT 3 (vb. foutdiagnose, Hardware toevoegen en procesparameters productielijn wegschrijven naar SQL DB)
          - Siemens TIA Portal S7, Simatic Manager STEP 7 (vb. foutdiagnose, Koelaggregaten inprogrammeren in bestaande machine)
          - Siemens WinCC (vb. Protool tekst gebaseerd HMI's omzetten naar WinCC volledige procesvisualisaties)
          - FANUC: teachen en programmawijzigingen robots, basis simulaties in ROBOGUIDE
          - Visie: Cognex, Keyence, Balluff (wijzigingen in bestaande visieprogramma's)
          - CAD: EPLAN electric P8
          
      - layout: left
        title: Digitalisatie
        description: | # this will include new lines to allow paragraphs
          - Programmeren: Visual Studio - VB.NET, C# (WinForms, MVC), HTML, CSS (vb. Webpagina voor tonen MS SQL database, 
          Automatiseren van resultaatverwerking metingen naar kwaliteitssysteem, Aansturen Keyence scanners en DMC gegevens wegschrijven naar Oracle DB.)
          - Smart tools: KNIME, RPA - UiPath, PowerBI 
          - Office 365: Outlook, Teams, Word, Excel, PowerPoint, OneNote, PowerApps
          
      - layout: left
        title: Andere
        description: | # this will include new lines to allow paragraphs
          - Soft-Skills: Leergierig, initiatief nemend, analytisch/ problem solving
          - Talen: Nederlands (Moedertaal), Engels (Zeer Goed), Frans (Basis), Duits (Basis)
  - title: Werkervaring # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Continental Automotive Benelux BV
        link: https://www.continental.com/en?lang=be
        # link_text: continental.com
        sub_title: Specialist Industrial Engineering Conditioning Area & PLV assembly 
        caption: November 2016 - Nu
        quote: >
          The future in motion!
        description: | # this will include new lines to allow paragraphs
          "Als werkvoorbereider IE heb ik technical ownership over twee productiezones. Hierbij sta ik in voor de continuïteit van de afdeling waardoor volgende zaken tot mijn takenpakket behoren: 
          Projecten uitwerken van A tot Z, Optimalisatiestudies (takttijd verbeteringen), PLC aanpassingen, Ondersteuning voor zowel kwaliteit als productie, intern en extern onderhoud coördineren, digitaliseren en verder automatiseren."
      - layout: left
        title: Caradon Stelrad N.V.
        link: www.stelrad.eu
        # link_text: boringcompany.com
        sub_title: Masterthesis student
        caption: 2015 - 2016
        description: | # this will include new lines to allow paragraphs
            Ontwerp maken voor laskop beugellasmachine (sterkteberekeningen, EEM-analyse, technische tekeningen, kostenraming), ontwerp realiseren, ontwerp testen, resultatenverwerking.
  - title: Opleidingen # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Certificaten
        caption: 2016 - NU
        sub_title: "On-the-job"
        description: | # this will include new lines to allow paragraph.
         Veiligheid: VOL/VCA (HaCeCo)
         
         Automatisatie: Basisopleiding FANUC (Anttec), Siemens S7-300 PLC basis en foutdiagnose (Anttec), TIA Portal WinCC (SITrain Siemens), EPLAN electric P8 (LimTec)
         
         Programmeren: Basis SQL en DB (ie-net), C# fundamentals (Syntra), UiPath Developer Foundation (UiPath Academy)
      - layout: left
        title: KU Leuven
        caption: 2014 - 2016
        sub_title: Master IIW
        description: | # this will include new lines to allow paragraphs
          Master Industriële Ingenieurswetenschappen Manufacturing Engineering
          
          bij Technologiecampus De Nayer in Sint-Katelijne-Waver.
      - layout: left
        title: KU Leuven
        caption: 2011 - 2015
        sub_title: Bachelor IIW
        description: | # this will include new lines to allow paragraphs
          Bachelor Industriële Ingenieurswetenschappen Elektromechanica
          
          bij Technologiecampus De Nayer in Sint-Katelijne-Waver.
      - layout: left
        title: Sint-Gabrielcollege
        caption: 2005 - 2011
        sub_title: ASO
        description: | # this will include new lines to allow paragraphs
          Wetenschappen Wiskunde 6u
          
          op het Sint-Gabrielcollege te Boechout.
          
# Footer
footer_show_references: true
references_title: Referenties op aanvraag

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
